# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 815d7727e00c51cc5c23d22e75f2271b73c97552971827febaee42637106e6b8dbe55b30856ac25a77eceb4923b79e7049f73e5e637f26881a53adcbdd69dbae

test:
  secret_key_base: 3597faea7af913fa5e788f4a5670a09984a34fefe4cbe890f412907bef14b6031f237f77582725ce624d13ef50746356e95f672b84f72cb5321252c24ca07715

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
